'''
389. Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
'''

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        # Initialize the variable to store the difference character
        result = 0
        
        # XOR all characters in both strings
        for char in s:
            result ^= ord(char)
        for char in t:
            result ^= ord(char)
        
        # The remaining value will be the ASCII of the extra character
        return chr(result)

# Example usage:
solution = Solution()
s = "abcd"
t = "abcde"
print(solution.findTheDifference(s, t))  # Output: "e"
